services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: mri_dbms_sql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrongPassword123!
    volumes:
      - mssql_data:/var/opt/mssql
      # Map your host backup folder to a internal folder called /backups
      - /mnt/DATA-DRIVE/Code/MRI_VECTORIZED_BACKUP:/backups 

volumes:
  mssql_data:
